### ISSUE TITLE
aeson 2.0 support

### ISSUE THREAD

**Issue by maralorn** [softwarefactory-project/matrix-client-haskell#22]
When trying to compile matrix-client with aeson 2.0 I get the following error. For compatibility with stackage-nightly this should be fixed when convenient. Thank you!
```
[3 of 7] Compiling Network.Matrix.Identity

src/Network/Matrix/Identity.hs:126:82: error:
    • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
                     with: HM.HashMap Text Value
      Expected: HM.HashMap Text Value
        Actual: aeson-2.0.3.0:Data.Aeson.Types.Internal.Object
    • In the first argument of ‘HM.toList’, namely ‘kv’
      In the second argument of ‘mapMaybe’, namely ‘(HM.toList kv)’
      In the second argument of ‘($)’, namely
        ‘mapMaybe toTuple (HM.toList kv)’
    |
126 |       (Object kv) -> pure . IdentityLookupResponse $ mapMaybe toTuple (HM.toList kv)
    |                                                                                  ^^
```

**Comment by TristanCacqueray** [comment]
Thank you for the heads-up. #23 seems to build with  `--constraint="aeson>=2.0"`. I'll upload 0.1.4.1 with it shortly.

**Comment by TristanCacqueray** [comment]
https://hackage.haskell.org/package/matrix-client-0.1.4.1 should now build with aeson 2.0
